


/////transaction////
class transaction;

    // Stimulus generated by Generator
    rand bit [7:0] txin;

    bit start;
    bit rx;

    // Values captured by Monitor
    bit tx;
    bit [7:0] rxout;
    bit txdone;
    bit rxdone;

    function void display(string name);

        $display("--------------------------------------");
        $display("%s", name);
        $display("txin   = %0h", txin);
        $display("start  = %0b", start);
        $display("rx     = %0b", rx);
        $display("tx     = %0b", tx);
        $display("rxout  = %0h", rxout);
        $display("txdone = %0b", txdone);
        $display("rxdone = %0b", rxdone);
        $display("--------------------------------------");

    endfunction

endclass
